spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://db:3306/authservice_db
        username: myuser
        password: mypassword

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
              format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
application:
    security:
        jwt:
            secret-key: A18E72AFC950A05D2BFC1736E052CB990031E91144BCF5BCB3DD35917235DC69
            expiration: 60000 # 86400000 # a day
            refresh-token:
                expiration: 604800000 # 7 days